### ISSUE TITLE
How to find initial Motion?

### ISSUE THREAD

**Issue by EmreOzkose** [hmgoforth/gps_denied_uav_localization#2]
I want to run this code with different data. Hence, i should find initial motion of image sequences (frames). I found 4 satellite map points in GIMP which corresponds to UAV frame. I replaced homography values in warp_hmg(img, p) with cv2.getPerspectiveTransform() homography as an initial motion. cv2.warpPerspective() works well, but when i put my H to "xy_warp = H.bmm(xy)", it gives a black image. How can i calculate initial motion. 

Note: i tried this experiment in Village.

**Comment by hmf21** [comment]
I have the same problem when I want to test this algorithm on the dataset made by my self. I calculate this p_init and p_org with function: cv2.findHomophy() and also get a black image. 
Do you have any better solutions?
Very appreciate!

**Comment by EmreOzkose** [comment]
Actually It was a small research project for summer and I am working on another project for a long time. Unfortunately, I don't remember :frowning_face:

**Comment by hmf21** [comment]
Hi @EmreOzkose 
Thanks for your reply and seems we both encounter this problem.
Hahaha, very regretful but still bless your research path success.
